name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What do you want to see?
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Value
      description: Who benefits and how?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What would be included (and excluded)?
    validations:
      required: true
